preload = /home/truonglangquan/.config/wallpapers/black-white.jpg
wallpaper {
    monitor = LVDS-1
    path = /home/truonglangquan/.config/wallpapers/black-white.jpg
}
wallpaper {
    monitor = 
    path = /home/truonglangquan/.config/wallpapers/black-white.jpg
}
splash = false
